#!/usr/bin/env perl

# Plugin for Foswiki - The Free and Open Source Wiki, http://foswiki.org/
#
# Copyright (C) 2023-2025 Michael Daum http://michaeldaumconsulting.com
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

use strict;
use warnings;

BEGIN {
  if (-e './setlib.cfg') {
    unshift @INC, '.';
  } elsif (-e '../bin/setlib.cfg') {
    unshift @INC, '../bin';
  }
  require 'setlib.cfg';
}

use Getopt::Long;
use Foswiki::Plugins::SolrPlugin::EventWatcher ();

# change process name
$0 = 'foswiki-watch';

my @files = ();
my $debug = 0;
my $vhosting = 0;
my $foswikiRoot = $ENV{FOSWIKI_ROOT};
my $throttle = 1;
my $parallel = 2;

GetOptions(
  "parallel=i" => \$parallel,
  "throttle=i" => \$throttle,
  "debug:1" => \$debug,
  "vhosting:1" => \$vhosting,
  "root=s" => \$foswikiRoot,
) or die "unknown parameter";

Foswiki::Plugins::SolrPlugin::EventWatcher->new(
  parallel => $parallel,
  throttle => $throttle,
  debug => $debug,
  vhosting => $vhosting,
  foswikiRoot => $foswikiRoot,
  files => \@ARGV,
)->start;

